### ISSUE TITLE
Ховеры правки

### ISSUE THREAD

**Issue by yahorbukhta** [AndrewMatsiash/Website#3]
![image](https://user-images.githubusercontent.com/65916399/112133084-5cbeb480-8bdc-11eb-8079-bd048829943e.png)
Элементы меню должны подсвечиваться красным при наведения мыши

![image](https://user-images.githubusercontent.com/65916399/112133271-94c5f780-8bdc-11eb-8110-c920d0aae486.png)
Это ссылки должны и они также должны иметь ховер

![image](https://user-images.githubusercontent.com/65916399/112133415-bd4df180-8bdc-11eb-8666-1545b0ffcf3f.png)
Нижняя серая панель с текстом также появляется по ховеру

![image](https://user-images.githubusercontent.com/65916399/112135781-364e4880-8bdf-11eb-995c-ca39c2652849.png)
И тут не ровно

**Comment by AndrewMatsiash** [comment]
![Снимок экрана 2021-03-24 155047](https://user-images.githubusercontent.com/74107101/112351977-6e3ab600-8cdb-11eb-9e5b-decaa7d7fc4b.png)
Я исправил ,но не  могу понять, почему  у тебя группа из форм неровно отображалось ,а у меня изначально всe  ровно отображалось , я приложил скрин..Это из-за разности браузеров?

**Comment by yahorbukhta** [comment]
Еще от разрешения экрана зависит может, используй последнюю версию хрома
